### ISSUE TITLE
User Provisioning: On user creation username will be taken same as email while it gets updated on patch request

### ISSUE THREAD

**Issue by UmeshRajani** [plone/plone.restapi#125]
Hello,

On user create request, user get created on plone with username and email both are same even in body, provided username and email are different.

It works fine in patch case.

Thanks

**Comment by tisto** [comment]
@UmeshRajani Thanks for reporting the issue. I guess I can reproduce it:

- Enable email as login
- Create user and provide both username and email
- User that has been created has provided email as both username and email, the username has been ignored in the "create user" request.

(please try to be a bit more specific on your next bugreports, that makes it easier for us to understand which means we can fix the issue even faster)

I wrote a test to document that behavior:

```
    def test_add_user_with_email_login_enabled(self):
        # enable use_email_as_login
        security_settings = getAdapter(self.portal, ISecuritySchema)
        security_settings.use_email_as_login = True
        transaction.commit()
        response = self.api_session.post(
            '/@users',
            json={
                "username": "howard",
                "email": "howard.zinn@example.com",
                "password": "secret"
            },
        )
        transaction.commit()

        self.assertEqual(201, response.status_code)
        user = api.user.get(userid='howard.zinn@example.com')
        self.assertTrue(user)
        self.assertEqual('howard.zinn@example.com', user.getUserName())
        self.assertEqual('howard.zinn@example.com', user.getProperty('email'))

```
https://github.com/plone/plone.restapi/commit/22bcafc4c15e947c298660f7548986f078947c82#diff-d352b5ad24d132d9bda062ba4d1e4e65R142


Though, I'm wondering why you would want to use email-as-login and then create another username. Could you elaborate that use case?

I mean you are not going to use that username in the first place, right? You use email for login anyways. We can handle this edge case differently, though we might want to stay with the current implementation (be liberal of what you accept) or reject that request in the first place because it does not make sense.

If you can provide us with a real use case for this, I'm happy to adapt our implementation of course!

@lukasgraf @sneridagh @buchi @zupo opinions?

**Comment by buchi** [comment]
I'm slightly favoring that it shouldn't be possible to create users with different username and email when the "use email as login" setting is enabled.

Right now there's an inconsistency with POST and PATCH. You can change the username to be different than the email if you update the user using PATCH, however if you create a new user using POST the username is ignored. At least both methods should behave the same way.

There's also a simplification with the _username_ I don't like. A user has a _user id_ and a _login name_. IMO it should be possible to create users with a different user id than the login name. It should also be possible to change the login name later using PATCH, but not the user id.

**Comment by UmeshRajani** [comment]
Thanks @tisto. 
Actually we are working on identity management solution, user provisioning can be done from OpenIDM to many application, like redmine, plone, etc. 

We are implementing SSO too for all of these applications and we have OpenAM as idp for authentication/authorization, and we are able configure OpenAM for either username or emailid  will be used to login in targeted application. So if we consider redmine case we can log in either using username or emailid.

As most of the application allow us to login in using both way useranme and emailid, so initially we made uniform structure of rest request body. But as @buchi said here we have inconsistent POST and PATCH so it will be confusing.

I think this question will make me clear:
Can it be possible to login in plone using both username and emailid?

Thank you

**Comment by davisagli** [comment]
https://github.com/plone/plone.restapi/pull/255 changed the user registration endpoint so that username is only allowed when email-as-login is disabled.
