### ISSUE TITLE
Admin logged in with jwt token is not able to do all workflow transitions

### ISSUE THREAD

**Issue by pabo3000** [plone/plone.restapi#127]
Steps to reproduce:
1. Create Plone site ( I used 4.3.9)
2. Install plone.restapi
3. Ask for possible transitions on front-page or any other doc using the rest api

```
GET front-page/@workflow HTTP/1.1
Accept: application/json
with Basic Auth   admin:admin
```

response:

```
{
  "history": [
    {
      "action": null,
      "actor": "admin",
      "comments": "",
      "review_state": "private",
      "time": "2016-07-15T12:52:31+02:00"
    },
    {
      "action": "publish",
      "actor": "admin",
      "comments": "",
      "review_state": "published",
      "time": "2016-07-15T12:52:31+02:00"
    }
  ],
  "transitions": [
    {
      "@id": "http://localhost:8080/test/front-page/@workflow/reject",
      "title": "Send back"
    },
    {
      "@id": "http://localhost:8080/test/front-page/@workflow/retract",
      "title": "Retract"
    }
  ]
}
```

Now ask the same but use the JWT. (Ask for it @login with Basic Auth admin:admin)
f.e.

```
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsbmFtZSI5bnVsbCwic3ViIjoiYWRtaW4iLCJleHAiOjE0Njg2MjMyNDN9.2iW5nJzHh0HgcY8CjRC5v0nnkSkTHAL-RUsL21fzdBY
```

the response is:

```
{
  "history": [
    {
      "action": null,
      "actor": "admin",
      "comments": "",
      "review_state": "private",
      "time": "2016-07-15T12:52:31+02:00"
    },
    {
      "action": "publish",
      "actor": "admin",
      "comments": "",
      "review_state": "published",
      "time": "2016-07-15T12:52:31+02:00"
    }
  ],
  "transitions": [
    {
      "@id": "http://localhost:8080/test/front-page/@workflow/retract",
      "title": "Retract"
    }
  ]
}
```

As you see you cannot reject despite you are admin.

**Comment by tisto** [comment]
@buchi any idea how this is related to JWT?

**Comment by buchi** [comment]
I guess this is because the JWT plugin is installed in the `acl_users` folder of the Plone site but the admin user is defined in the root `acl_users` folder. The user only gets roles from the `acl_users` folder he got authenticated in.
Thinking more about that, I think it's wrong to login users that are defined in an `acl_users` folder that doesn't contain a JWT plugin. We should change that behavior in the `@login` endpoint.

Simple workaround: Use only users that are defined in the Plone site.

If we need support for users defined in the Zope root, the PAS plugin also needs to be installed there. However that might not work out-of-the-box as we are depending on Plone's keyring which is only available in a Plone site.

**Comment by tisto** [comment]
Will close this issue for https://github.com/plone/plone.restapi/issues/178
