### ISSUE TITLE
Restrict the number of languages used in the test setup.

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#132]
Our current test setup includes all languages that Plone provides. This makes pull request and test outputs very hard to read. Example:

https://github.com/plone/plone.restapi/pull/131/files#diff-90d54f527ebe8f893a2562344de8b07fR491

I already looked into it but I currently don't have time to work on it. Any takers?

**Comment by lukasgraf** [comment]
I also noticed this again yesterday, and it bugged me so much that I took another stab at it, but with no immediate success.

The vocabulary listing those languages is [`plone.app.vocabularies.AvailableContentLanguages`](https://github.com/plone/plone.app.vocabularies/blob/ff9201f5e9772da621a362155a400d66c6148e34/plone/app/vocabularies/language.py#L11-L56). This vocab simply takes the languages from `portal_languages.getAvailableLanguages()`, which in turn gets them [from a `IContentLanguageAvailability` utility](https://github.com/plone/Products.PloneLanguageTool/blob/ebb7fe9a2188b7e0ec2a97fd829afac2faefdd24/Products/PloneLanguageTool/LanguageTool.py#L202).

This is where it gets slightly weird. `plone.i18` defines and registers a [`ContentLanguageAvailability` utility](https://github.com/plone/plone.i18n/blob/7b859ce79404af7aeee89f9b2b3f5b2785d97596/plone/i18n/locales/languages.py#L39-L44), that gets all the languages from a module global list. My first approach was therefore to override that utility. However, re-registering a utility for the same interface in our `testing.zcml` (no `overrides.zcml` yet) I wasn't able to produce a `ConfigurationConflict`.

The reason seems to be that what actually ends up being used is `<ContentLanguages at /plone/plone_app_content_languages>`, [a persistent local utility from plone.**app**.i18n](https://github.com/plone/plone.app.i18n/blob/0fe6bf7c733b0cecafa68d0e63bbe861212c4bcd/plone/app/i18n/locales/languages.py#L52-L65).

So I'll see whether I can manage to override that cleanly from our test setup. A different option would be to monkey patch [`_languagelist`](https://github.com/plone/plone.i18n/blob/7b859ce79404af7aeee89f9b2b3f5b2785d97596/plone/i18n/locales/languages.py#L61) and [`_combinedlanguagelist`](https://github.com/plone/plone.i18n/blob/7b859ce79404af7aeee89f9b2b3f5b2785d97596/plone/i18n/locales/languages.py#L258) module globals in `plone.i18n.locales.languages`, but I'd rather avoid that if at all possible.
