### ISSUE TITLE
Types Schema: JSON Schema code samples are not JSON Schema

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1370]
https://6.dev-docs.plone.org/plone.restapi/docs/source/types-schema.html

For example, this looks like Python, not JSON Schema.

```
{
    'type': 'string',
    'title': u'My field',
    'description': u'My great field',
    'default': u'foobar',
}
```

JSON Schema is a lot more verbose than this, so I am not sure what to make of this.

**Comment by tisto** [comment]
@stevepiercy it is not valid JSON because it uses single quotes. We use a subset of JSON schema, not the full standard and we might even derive from it. I guess this needs a better explanation. 

This page is basically and extension to the "schema GET" we are describing here:

https://6.dev-docs.plone.org/plone.restapi/docs/source/types.html#get-the-schema-with-get

The idea is that this particular page lists all the possible outcomes of the JSON schema definitions that you can get with the current set of zope.schema.

**Comment by jensens** [comment]
IMO this should be valid JSON not Python. The idea is, as far as I understand, to show a snippet how it is defined in Python and then how it will be translated in JSON and transferred out.

(And OT here, but the u-strings are gone in Python 3)
