### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ksuess** [plone/plone.restapi#1453]
Please release plone.restapi: All four PRs needed for user group membership control panel are merged. Would you do a release, @tisto , thanks.

**Comment by jensens** [comment]
We should have more than one person for this task? If not we need the @plone/release-team

**Comment by mauritsvanrees** [comment]
What's the rush?  A new release will be included in the first beta, no worries about that. If there is an urgent need, then yes I can release, but I would wait for Timo otherwise.

I have done a ton of releases this year for other packages, and Timo feels responsible for this one and he checks to make sure it fits with Volto, so I would rather wait for him to do it.

Is there still a functional @plone/restapi-team with people feeling comfortable reviewing and merging PRs, and maybe also releasing?

**Comment by jensens** [comment]
No idea, sounded like its urgent :-/ probably it was not, sorry for the noise.

**Comment by ksuess** [comment]
This is about providing a control panel managing user group memberships for Volto: https://github.com/plone/volto/pull/3349#issue-1229512047
No rush, Plone 6 can do without.

**Comment by jensens** [comment]
Ok, so lets note, its very important for the beta if not before.
