### ISSUE TITLE
Expansion (was: Framing Proposal)

### ISSUE THREAD

**Issue by lukasgraf** [plone/plone.restapi#149]
This will be the proposal for the framing implementation in `plone.restapi`.

See #6 for prior discussions.

The proposal is currently being worked on in this Google Doc, and will later be moved into this issue: https://docs.google.com/document/d/17IiOqetuNQNBdtosPdMC-VejKZFyhQZHnCX9VG6SEoM/edit

**Comment by tisto** [comment]
Framing/expansion has been implemented here by @buchi:

https://github.com/plone/plone.restapi/pull/153

@bloodbare if you have time please have a quick look and let us know if this implementation is in sync with plone server.

**Comment by tisto** [comment]
Closed https://github.com/plone/plone.restapi/pull/153

**Comment by ebrehault** [comment]
@tisto @lukasgraf @buchi in the original issue (https://github.com/plone/plone.restapi/issues/6), we mentioned the `actions` expandable component. Is it still something we are considering?

It would definitely be very useful to implement the toolbar in frontend projects.

**Comment by buchi** [comment]
@ebrehault "actions" is definitely something we should consider. However I'm not sure yet how to implement that. The problem is that the actions defined in "portal_actions" are not very suitable for use in plone.restapi as they contain urls to web forms. So the question is how do we determine available actions? And how can one register additional actions? We could use our own action categories in "portal_actions" but with those it's not possible to provide additional infos like e.g. the request method. Thus I would favor some sort of our own actions registry in plone.restapi. Maybe we can simply use the service registry from plone.rest. But that's something that has to be discussed in more detail.

**Comment by ebrehault** [comment]
I agree we do not care about "how" the action should be performed (=the
url), but we do care about "what" acion we are allowed to perform in a
given context.
So it does look like a set of "permissions", but they are probably not
actual Plone permissions which are too low level. What we call actions in
Plone are high-level enough, and are actually useful on the frontend.
We just need an endpoint providing the id and labels of the actions.
(an endpoint providing actual persmissions might be useful in some cases
too, though).

On Sun, Aug 6, 2017 at 12:59 PM, Thomas Buchberger <notifications@github.com
