### ISSUE TITLE
Locking created date without timezone information.

### ISSUE THREAD

**Issue by iFlameing** [plone/plone.restapi#1551]
1. Have to use Universal time and not local time.
2. We want to add z at end of serialized time string because IsoFormat is not doing that.

This will create a serialized time string then javascript correctly formats to the local time of the user in frontend with timezone information.

**Comment by flipmcf** [comment]
In a restapi dump of an object, I noticed that only 'effective' and 'expires' seem affected by this.   Is your behavior the same?

My local time is -4 hours - US Eastern.   This is an object that was created and published very quickly for testing purposes, and the restAPI gave back these dates:


```
"created": "2023-05-15T14:41:17+00:00",
...
"effective": "2023-05-15T10:45:00",
"expires": "2025-05-16T10:45:00",
...
"modified": "2023-05-15T14:45:24+00:00"
...
"workflow_history": {
        "story_workflow": [
            {
                "action": null,
                "actor": "tester",
                "comments": "",
                "review_state": "private",
                "time": "2023-05-09T14:44:49+00:00"
            },
            {
                "action": "publish",
                "actor": "tester",
                "comments": "",
                "review_state": "published",
                "time": "2023-05-09T14:45:02+00:00"
            }
        ]
    }
```

**Comment by davisagli** [comment]
@flipmcf This issue is specifically about the date in the locking info, and I have a fix in progress for that one in #1647 

I would not assume that the problem with the effective and expires dates is the same. It matters whether the dates are Python date vs Zope DateTimes, whether they are timezone-naive or not, and which service is serializing them. Could you please open a new issue that includes the specific steps to reproduce the problem with effective and expires? I'm happy to take a look but I'd rather keep this separate from the other timezone issues that I've already looked at.

**Comment by flipmcf** [comment]
I uncovered it here: https://github.com/collective/collective.exportimport/issues/206

**Comment by flipmcf** [comment]
disregard my comments.  Wrong ticket.

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/plone.restapi/pull/1647
