### ISSUE TITLE
Search users endpoint

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#170]
We need:

1) API design (resource modeling)
2) Implementation (should be efficient with ldap and other PAS sources)

**Comment by sneridagh** [comment]
I'm trying to implement an users search endpoint for using it in autocomplete widgets. I did a first attempt of implementation here:
https://github.com/plone/plone.restapi/pull/171

The first approach I tried is to use the acl_users.searchUsers function since it searches through all the IUserEnumerationPlugin plugins.

@tiso @buchi @lukasgraf Do you think that this is any other good approach for search?

I'm really concerned about the performance of waking up the full member info. I'm not in favor of doing a dangerous potential operation like calling getMemberById that could easily escalate in terms of load. I've been there using big LDAPs, of course this happened also because the LDAP plugin is poorly written. Any insights about this?

**Comment by tiso** [comment]
OT: guys, please, don't mention me.
