### ISSUE TITLE
IBlocks SearchableText indexer bypasses plone.textindexer behavior

### ISSUE THREAD

**Issue by tlotze** [plone/plone.restapi#1744]
The `SearchableText_blocks` indexer combines searchable text from blocks with the result of calling the base searchable text extractor, which is hardcoded to be `plone.app.contenttypes.indexers.SearchableText`. However, if the `plone.textindexer` behavior is active, it will be bypassed by this, so `IDynamicTextIndexExtender` adapters won't be used.

Given the way the component architecture handles adapter lookups, there may be no clean solution to call "whatever would have been called for a searchable text indexer if the `IBlocks` one wasn't in place". Another solution would be to turn the logic upside-down and implement the `IBlocks` indexer as an `IDynamicTextIndexExtender` adapter, which would require the `plone.textindexer` behavior to be implied by using Blocks.

I'm not sure what the best or cleanest solution might be. However, Blocks competing with `plone.textindexer` for the actual indexer feels unexpected and possible solutions feel hacky.

**Comment by davisagli** [comment]
This does look a bit tricky. Perhaps we could implement the blocks indexer as an IDynamicTextIndexExtender, like you suggested, and also make IBlocks extend IDexterityTextIndexer, so that enabling blocks implicitly enables the `plone.textindexer` indexer. But, the fact that plone.restapi still aims to be compatible with Plone 5 will make the backwards-compatibility tricky.

**Comment by wesleybl** [comment]
See: #1764
