### ISSUE TITLE
Add support for all plone.autoform tagged values

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#213]
This is a follow up of https://github.com/plone/plone.restapi/issues/198. We should support all tagged values that are defined in plone.autoform:

```
MODES_KEY = u"plone.autoform.modes"
OMITTED_KEY = u"plone.autoform.omitted"
ORDER_KEY = u"plone.autoform.order"
WIDGETS_KEY = u"plone.autoform.widgets"

READ_PERMISSIONS_KEY = u"plone.autoform.security.read-permissions"
WRITE_PERMISSIONS_KEY = u"plone.autoform.security.write-permissions"

```
https://github.com/plone/plone.autoform/blob/master/plone/autoform/interfaces.py#L13

**Comment by lukasgraf** [comment]
I took this up at the Beethoven Sprint, and while for certain `plone.autoform` directives (omitted, mode, permissions) it's as simple as just exposing the tagged values (assuming IRO has been properly honoured), that's not the case for **`fieldset`** and **`field_order`** directives.

Those require some advanced interpretation in order to achieve a meaningful result. I therefore overhauled the way that the JSON schemas are built in the `@types` endpoint, see #237

**Comment by tisto** [comment]
Merged in https://github.com/plone/plone.restapi/pull/237
