### ISSUE TITLE
Images in richtext fields should have full path

### ISSUE THREAD

**Issue by ebrehault** [plone/plone.restapi#302]
Currently we get things like:
```
<img class=\"image-inline\" src=\"../../resolveuid/719b8d0f763c4695a9c988005c6990c0/@@images/image/large\" alt=\"\" data-linktype=\"image\" data-scale=\"large\" data-val=\"719b8d0f763c4695a9c988005c6990c0\" />
```

We want:
```
<img class=\"image-inline\" src=\"https://mybackend.net/resolveuid/719b8d0f763c4695a9c988005c6990c0/@@images/image/large\" alt=\"\" data-linktype=\"image\" data-scale=\"large\" data-val=\"719b8d0f763c4695a9c988005c6990c0\" />
```

**Comment by tisto** [comment]
@ebrehault right. That might not be trivial to accomplish. We would need a custom portal transform I guess.

**Comment by erral** [comment]
I think that this could be fixed calling `output` instead of `raw` in the RichText field serializer

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/converters.py#L139

**Comment by erral** [comment]
I tested manually changing `raw` with `output` and it works for links.

In the Archetypes serializer we need something similar, we need to call directly to `getAccessor` instead of checking first `getEditAccessor`, because when checking this we are calling to `getRaw<Fieldname>` method instead of `get<Fieldname>`

**Comment by ebrehault** [comment]
sounds like a good approach
