### ISSUE TITLE
Unifying AT/DX tests

### ISSUE THREAD

**Issue by jaroel** [plone/plone.restapi#323]
The tests for serialising and deserialising AT and DX should (in most cases) be thesame code.
It would be awesome to group the tests and use them in both the AT and DX tests.
ie using a tests mixin for, for example, getLayout and the reordering stuff.

**Comment by gforcada** [comment]
Should we care that much about AT? In Plone 6 it will not be supported anyway and testing wise, since we moved to Plone 5 and packages layers start depending on p.a.contenttypes is being tested less and less.

Don't see that comment above as stop energy, sorry if it sounded like that, but rather as a re-focus energy 😄

**Comment by jaroel** [comment]
It's fine by me

**Comment by davisagli** [comment]
Support for Archetypes was dropped already
