### ISSUE TITLE
Test coverage dropped below 100%.

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#33]

**Comment by tisto** [comment]
```
Name                                          Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------
src/plone/restapi/__init__                        2      0   100%   
src/plone/restapi/demo/__init__                   0      0   100%   
src/plone/restapi/demo/demo                       0      0   100%   
src/plone/restapi/interfaces                      5      0   100%   
src/plone/restapi/serializer                     73      7    90%   116, 122, 190-197
src/plone/restapi/services                        8      2    75%   9, 33
src/plone/restapi/testing                        17      0   100%   
src/plone/restapi/tests/__init__                  0      0   100%   
src/plone/restapi/tests/test_documentation      135      0   100%   
src/plone/restapi/tests/test_error_handling      50     30    40%   37-48, 52-65, 72-84, 91-113
src/plone/restapi/tests/test_serializer          73      0   100%   
src/plone/restapi/tests/test_services            75      0   100%   
src/plone/restapi/tests/test_setup               13      0   100%   
src/plone/restapi/tests/test_utils               41      0   100%   
src/plone/restapi/utils                          25      0   100%   
---------------------------------------------------------------------------
TOTAL                                           517     39    92%   
```

**Comment by lukasgraf** [comment]
Tests using a [`z2.ZSERVER`](https://github.com/plone/plone.testing/blob/master/src/plone/testing/z2.py#L974) fixture, like those on [`PLONE_RESTAPI_FUNCTIONAL_TESTING`](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/testing.py#L33), don't seem to be picked up by `coverage.py`.

I'm assuming this is because `coverage.py` can't trace threads that are instantiated using the low-level `thread` interface instead of the higher level `threading` module (see [coveragepy#244](https://bitbucket.org/ned/coveragepy/issues/244/coverage-doesnt-work-with-thread-not) and [`ZServer.PubCore.ZRendezvous`](https://github.com/zopefoundation/Zope/blob/master/src/ZServer/PubCore/ZRendezvous.py#L14)).

So... Functional tests using a Z2 server and the `requests` module won't have their coverage recorded.

**Comment by tisto** [comment]
Yep. That seems to be the problem. This is not limited to plone.restapi though.

**Comment by tomgross** [comment]
You can enforce a minimun of tests to be covered with nose:

> --cover-min-percentage=DEFAULT
>     Minimum percentage of coverage for tests to pass [NOSE_COVER_MIN_PERCENTAGE]

See:
http://nose.readthedocs.org/en/latest/plugins/cover.htm

**Comment by witsch** [comment]
Test coverage is back to 96% with https://github.com/plone/plone.restapi/issues/238, but the rest will probably take some (tedious) work.  I support you might want to close this anyway… :)

**Comment by tisto** [comment]
Wohoo! Yeah. Will close this one and create a new ticket...
