### ISSUE TITLE
Support for relation fields

### ISSUE THREAD

**Issue by jone** [plone/plone.restapi#43]
We should support relation fields.
I think we should have a general short-form for representing content which can use when representing **relations** but also for **children**, **parent** and more.
How do we do that?

**Comment by tisto** [comment]
What about a URL to the referenced object (that can be expanded)? We should also add a "parent" pointer (I think I already did that in a branch somewhere).  Children are already covered by the JSON-LD "member" list, right?

**Comment by jone** [comment]
Yes, sure. I just think we should use the same format (and thus the same code) for such references, e.g.:
```js
{
"@id": "http://nohost/plone/foo/very-important-news",
"title": "Very important news"
}
```
It would be great if all those pointers look the same.

**Comment by lukasgraf** [comment]
> It would be great if all those pointers look the same.

Agreed, as long as we can work with a loose enough definition of "the same" :grinning: I'd say "the same" in the sense that it should always be a dictionary with an `@id` where the complete resource can be found, and `0 - n` metadata fields, depending on context (and possibly a client-supplied parameter like `field_list`).

Because in some contexts, the 95% will be just rendering a link - so the target URL and `title` might be enough. In other contexts, you'll need more of the metadata of referenced objects (search results for example must already include things like portal type and author to be useful).

**Comment by tisto** [comment]
If you need a different representation of the relations we might want to create another frame to render the JSON differently.

**Comment by lukasgraf** [comment]
:+1: framing sounds like the proper way to go about this

**Comment by lukasgraf** [comment]
Summary representations have been unified in #71.

Relation fields are now serialized to a summary like this, same as parent pointers, children, search results and collection items:

```json
{"@id": "http://nohost/plone/doc1",
 "@type": "Document",
 "title": "Referenceable Document",
 "description": "Lorem Ipsum"
 }
```
