### ISSUE TITLE
Managing Dexterity Type Creation (CRUD) via plone.restapi

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#534]

**Comment by avoinea** [comment]
@tisto Would it be feasible to accomplish this by using the `@types` endpoint and implement the missing`POST`, `PATCH` and `DELETE`?

Thus, we'll have:


Verb | URL | Action
-- | -- | --
POST | /@types | Creates a new content-type
GET | /@types/{type:id} | Already implemented (we should also list behaviors)
PATCH | /@types/{type:id} | Update content-type
DELETE | /@types/{type:id} | Remove content-type

**Comment by tisto** [comment]
@avoinea yeah. I guess that makes sense. I would recommend that you follow our documentation-first approach and start writing the docs for the new enhanced endpoint. Then we can discuss the API design based on your PR. If you want we can also schedule a hangout this week to discuss this in more detail (in addition to our early adopters' hangout on Friday)...

**Comment by avoinea** [comment]
#907 initial pull-request submitted.

For now it covers dexterity types:
* listing
* content-type:
  * create
  * read
  * update
  * delete

We used the `/@controlpanel/dexterity-types` endpoint instead of `/@types` in order to have a better control on used permissions.

TODO:
* `@behaviors` - Enable/Disable behaviors on content-type
* `@schema` - Add/Remove fields
* `@layout` - Blocks - initialBlocks, requiredBlocks

Please add your PRO and CONS on this approach or your other vision.
