### ISSUE TITLE
Complete the experience when using choices/lists tied to vocabulary/sourceCatalog fields

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#535]
Currently choices or list-choices fields are returning all the possible values in the content type JSON Schema representation, and that could lead to returning big datasets that the browser have to deal with (and probably fail to do so, hanging up).

Instead, we have to find out to provide a better experience with those, in which could be easily integrated with an autocomplete widget that would query to the original vocabulary, filtering the results on the fly.

Also, the sourceCatalog vocabulary field implementation is missing. Given the fact that is the recommended way to go when dealing with content in vocabularies (plone.app.vocabularies.Catalog), it's sensible to give support to them.

It might be needed to discuss how to implement that. Also, the UI can't alone determine which Component have to use for the widget (e.g subjects (Tags) field). We have to deliver some sensible defaults for the most common field-widget combinations as we did for z3c.form, but it would be great to be able to fine grain specify the type of the widget (in the UI or in Plone itself, when creating the field). More like

```
    directives.widget(
        'subjects',
        AjaxSelectFieldWidget,
        vocabulary='plone.app.vocabularies.Keywords'
    )
```

but thinking specifically on the UI part.

**Comment by davisagli** [comment]
The way that this currently works with mockup is:

1. The AjaxSelectWidget pattern options have `vocabularyUrl` set to an endpoint for looking up vocabulary terms. For fields with a vocabulary this is `[form path]/@@getVocabulary?field=[field name]` (so that permission to access the vocabulary can be checked based on the form context). For fields with a source this is `[widget path]/@@getSource`
2. The select2 and relateditems widgets in mockup call these endpoints, passing either a string or a querystring-formatted query.
3. The getVocabulary and getSource views are implemented in plone.app.content. They handle a few different things:
    - Get the vocabulary.
    - Check permission using either a IFieldPermissionChecker adapter or a hardcoded mapping of vocab name to permission.
    - Prepare a catalog query. The query is found in the `query` request parameter, which can be either a string or JSON including a `criteria` querystring, `sort_on`, and `sort_order`.
    - Search the vocabulary:
        - If the vocabulary factory takes a `query` parameter, call it passing the query.
        - If the vocabulary has a `search_catalog` method, call it passing the query.
        - If the vocabulary has a `search` method, call it with the SearchableText from the query.
        - Otherwise (or if no query) iterate through all terms.
    - Batch results.
    - Serialize results. Each item includes `id` and `text` unless additional attributes were requested with the `attributes` param, in which case it tries to get those attributes from the vocab values (this is used with catalog brains from the catalog vocab).

This feels like quite a mess and trying to mix too many use cases. For plone.restapi I'd suggest something like this:

1. Add support to the existing `@vocabularies` service for passing a (string) query and batch start/size.
2. When serializing schema fields with named vocabularies, just include the URI of the `@vocabularies` endpoint for the vocab, rather than the serialization of all the terms.
4. Make the select and array widgets in plone-react and/or other frontends fetch choices from the `@vocabularies` endpoint.
5. Don't try to support related items fields (i.e. fields using the plone.app.vocabularies.Catalog vocabulary) or fields with sources using the same endpoint. Related items can probably use the `@search` endpoint, and sources will need a new endpoint that can look up the source for a particular field in a particular context.

**Comment by tisto** [comment]
1) ok, we have to think about permissions for the vocabularies endpoint
2) ok
3) ok
4) ok

Don't query the vocabularies endpoint when viewing existing form values in the frontend. The plone.restapi response should embed the id/title of the chosen vocabulary term.
