### ISSUE TITLE
Writing to disc when installing the egg (buildout or pip)

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#572]
#568 introduced a write on the disc on egg installation at the root of the project, @lukasgraf is that correct? It might lead to some errors on buildout and pip deployments where the permissions does not allow that.

**Comment by sunew** [comment]
@sneridagh I think we have to change this...

Thinks have become too entangled here.

I suggest separating the test step of the documentation, and the actual documentation generation. Two different things.

The test_documentation could write to a folder in tests, and test for left over artefacts. This folder would be ignored in .git

The actual generation of the documentation snippets should happen in a buildout step when building the project.

**Comment by lukasgraf** [comment]
@sneridagh I'm not exactly sure I understand what you mean. Those files should get written to *inside* the `.egg`, not the project root (?).

So, while before we had

`.../site-packages/plone.restapi-3.1.1.dev0-py2.7.egg/plone/restapi/`

we now also have

`.../site-packages/plone.restapi-3.1.1.dev0-py2.7.egg/docs/source/_json/`

Or what do you mean? Do you have an actual issue you're encountering?

**Comment by sneridagh** [comment]
@lukasgraf @sunew 
It failed to me when trying to build the updated docker image for this version which is pip powered, so it tried not to write on the egg level, but where I triggered the installation (./bin/pip). I can check if that happens too with buildout.

**Comment by sneridagh** [comment]
@lukasgraf @sunew It works well with buildout. It might seem to be on the pip install deployment. Not important then, but does it ring some bell?

**Comment by lukasgraf** [comment]
The [`setuptools` docs for `data_files`](https://docs.python.org/3/distutils/setupscript.html#installing-additional-files) do say, that `data_files` are installed relative to `sys.prefix` (or `sys.exec_prefix` respectively.

That is not what I've been seing with buildout and/or `easy_install`. It seems that `pip` might behave differently here. But still, that is using an official Python packaging API: If that's broken in the docker image, that could cause issues with other packages that use this mechanism as well.

I'm all for lending you a hand if you have issues, or we might even want to revert my change until we figure out what exactly is going on.

But please lets not throw out the baby with the bathwater here - building the test artifacts during buildout time is a horrible idea in my opinion (if that even works, because of dependencies).

Separation of building test artifacts, maybe also into a directory inside a python package so they can be distributed with `package_data`, and their actual inclusion in docs, could help however.

**Comment by sunew** [comment]
@lukasgraf my comment was not completely thought through ;)

Its not building test artefacts during build, but building the documentation artefacts during build I had in mind. I would cerainly still build the test artefacts and check it during tests - this is very valuable.

As you say: "Separation of building test artifacts (maybe also into a directory inside a python package so they can be distributed with package_data), and their actual inclusion in docs could help however."

**Comment by lukasgraf** [comment]
I was able to reproduce the behavior you described using `pip` - that's unfortunate indeed, and not what I intended. With `pip`, it actualy behaves as described in [setuptools docs for `data_files` ](https://docs.python.org/3/distutils/setupscript.html#installing-additional-files), which we don't want.

I believe simply moving the test artifacts inside `src/plone/restapi/tests/` and using `package_data` / `MANIFEST` to include them might already do the trick - then the artifacts get shipped as first class package data, and everything else should work. I'll look into it.

**Comment by sunew** [comment]
@lukasgraf +1

**Comment by sneridagh** [comment]
@lukasgraf as I said, I think the issue is not that important enough to revert given the fact that the pip install/deployments are not official, but it's something that might bite us in the future. Thanks!.

**Comment by lukasgraf** [comment]
@sneridagh Yeah, it's definitely not what I intended with this change, sorry. Fix is on the way.
