### ISSUE TITLE
Endpoint should report an error if no valid json can be generated

### ISSUE THREAD

**Issue by agitator** [plone/plone.restapi#673]
I was creating my own endpoint and was wondering for some time why I didn't get json as an output but the python dict structure.

As it turned out some values where "missing.value" or "None" and therefore no json could be produced.
Only when I converted the result into json with `json.dumps(result)`the mistake got visible.

Shouldn't the endpoint report an error if output as json fails instead of outputting the python structure? Opinions?

**Comment by lukasgraf** [comment]
@agitator did you inherit from the [`plone.restapi.services.Service`](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/__init__.py#L12-L34) base class?

This is the most straightforward way to implement your own service (you'd inherit from it, and just override `Service.reply()` with our own, returning a Python data structure that then gets serialized to JSON for you).

This base blass definitely doesn't swallow any exceptions during serialization. Can you provide steps to reproduce your issue? Maybe with a mock-implementation of what your service looks (directly returning a hard-coded `missing.value` instead of involving catalog etc..), or a failing test?

**Comment by agitator** [comment]
Used bobtemplates to generate the boilerplate and it uses `plone.restapi.services.Service`


This is what I'm playing around with, nowhere near to be finished or pretty ;-)
```
# -*- coding: utf-8 -*-
from plone import api
from plone.restapi.interfaces import IExpandableElement
from plone.restapi.services import Service
from zope.component import adapter
from zope.interface import implementer
from zope.interface import Interface
from plone.app.contentlisting.interfaces import IContentListingObject
import json


@implementer(IExpandableElement)
@adapter(Interface, Interface)
class Contents(object):

    def __init__(self, context, request):
        self.context = context.aq_explicit
        self.request = request

    def build_tree(self, brains):
        ret = {}
        for brain in brains:
            pathkey = "/".join(brain.getPath().split("/")[:-1])
            pathkey
            if pathkey in ret:
                ret[pathkey].append(IContentListingObject(brain))
            else:
                ret[pathkey] = [IContentListingObject(brain)]
        return ret

    @property
    def itemtree(self):
        items = api.content.find(
                    path="/".join(self.context.getPhysicalPath()),
                    depth=-1,
                    sort_on="getObjPositionInParent"
                    )
        tree = self.build_tree(items)
        for key, items in tree.items():
            tree[key] = map(
                lambda item: {
                    "@id": item.getURL(),
                    "uid": item.uuid(),
                    "title": item.Title(),
                },
                items,
            )
            print tree[key]
        return tree

    @property
    def start_path(self):
        root = self.context
        start_path = None
        if root:
            start_path = "/".join(root.getPhysicalPath()[:-1])  # start a level above the start context. itemtree structure works that way.  # noqa
        return start_path

    def __call__(self, expand=False):
        """Reply to REST/JSON requests.
        """
        self.request.response.setHeader('Content-Type', 'application/json')
        result = {
            'contents': {
                '@id': '{}/@contents'.format(
                    self.context.absolute_url(),
                ),
            }
        }

        # === Your custom code comes here ===
        result['contents']['items'] = self.itemtree
        return result


class ContentsGet(Service):

    def reply(self):
        service_factory = Contents(self.context, self.request)
        return service_factory(expand=True)['contents']
```

**Comment by lukasgraf** [comment]
Steps to reproduce please? As a minimal, verifiable example that demonstrates the issue on the `plone.restapi` side? (*"instead of involving catalog etc.."*).

At this point I don't quite understand what the supposed faulty behavior on the `plone.restapi` side is you're describing. If that's the service that's registered in ZCML, your `ContentsGet` will always return JSON.

Unless you return a [`_no_content_marker`](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/__init__.py#L9) in your `reply()`, in which case it would produce `204 No Content` with an empty body. Python `None` would be serialized to `null`.

**Comment by agitator** [comment]
Thanx for the clarification :-) I'll play some more with it and will reopen if needed.
