### ISSUE TITLE
Add QueryString resolver endpoint

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#789]
We are implementing a collection tile that should be able given a querystring, return the results from it. For this, we are using the recently merged @querystring endpoint to get the config, and we now need the mentioned one.

We have doubts about how to model this endpoint, since it's naturaly a GET but the potential serialization querystring that we should send is complex enough to discourage it. So we were thinking in using a POST to @querystring with the Plone querystring syntax in JSON in the BODY.

@lukasgraf @buchi @tisto @robgietema What do you think?

**Comment by lukasgraf** [comment]
Yeah, besides the complexity of properly encoding the data for use in a ?foo=bar QS, there's also the problem with URLs getting too long. In my experience, above 2000 characters you're prone to run into issues with webservers, proxies and certain versions of IE, and above 4000 you almost certainly will.

Also: The naming clash between the concepts of a HTTP query string (?foo=bar) and Plone querystring would be a pain in the butt to deal with.

We had a discussion in the past about using GET requests with a Request Body, and at that point we decided not to use it because it's quite rare. However, these days I'm not so sure if I feel the same way about this. [ElasticSearch uses GET requests with Request Bodies](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html) in their API for example.

So I could possibly see the option of allowing both `GET` and `POST` with a request body.

However, I'm not sure whether overloading the `@querystring` endpoint with the functionality to _fetch actual results_ is a good idea though. Currently it's an endpoint that exposes the querystring _configuration_.

**Comment by sneridagh** [comment]
@lukasgraf Right now I was modeling how the action would look like in Volto and I had the same feeling. Overloading the @querystring endpoint seems like too much. I'm also +1 to explore the GETs with requests BODY and probably allow both. Any idea on how to name this new endpoint to retrieve actual Plone collections querystring results?

**Comment by sneridagh** [comment]
@lukasgraf just had a wild idea: it's a search results, right? but using an specific DSL, the one we invented with p.a.querystring... why don't allow @search to handle that?

**Comment by lukasgraf** [comment]
I think at this point you're basically looking at the query_builder_ part of `plone.app.querystring`'s functionality. The `@querystring` endpoint currently pretty much directly exposes the classic Plone view [`querybuilderjsonconfig`](https://github.com/plone/plone.app.querystring/blob/a1e4e2516b62724cf6f078b01a42db8844906acb/plone/app/querystring/configure.zcml#L56-L61) via the REST API.

So now you're looking at exposing the [QueryBuilder](https://github.com/plone/plone.app.querystring/blob/a1e4e2516b62724cf6f078b01a42db8844906acb/plone/app/querystring/querybuilder.py#L41-L206) functionality I think.

So, one option would be to

1) Purely expose the **query building** functionality, e.g. with `@querybuilder`. Takes in a querystring, returns a ZCatalog compatible query (as a Python dict, serialized to JSON). That could then be sent to `@search`. But this would require two requests, which kind of sucks.

The other option would be to 

2) Expose the query _building_ and _querying_ as **combined functionality**. This could be done either 
2a) in a dedicated endpoint (`@querystring-search` or something like that (ugh))
2b) be integrated into `@search`

I think integrating it into `@search` would make sense to a degree, but it's also going to be nasty. Not so much from an implementation standpoint (I think that should work, the parts for parsing the query and handling serialization of the results should be quite clearly separated, IIRC). But from a "how do we describe this API without driving people insane" kind of standpoint ;-)

So yeah, integrating it into `@search` also crossed my mind - but I'm not quite sure yet whether it's a good idea. I'd love to hear some more opinions on this.

**Comment by sneridagh** [comment]
@lukasgraf yeah, I agree that overloading `@search` endpoint from the outside point of view can be confusing and better be redundant than confuse people. Searching for a name that does not seems forced is going to be hard `@querystring-search` or `@querystring-results` are not appealing indeed.

**Comment by tisto** [comment]
My 2c: We should not overload the search/querystring endpoint. Let's go with "querystring-search" until we find a better name. Zope does not allow to use a body in a GET request so let's go with a POST + search query in the body.

Are you ok with that @plone/restapi-team?

**Comment by sneridagh** [comment]
Implemented some months ago
